import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../models/expense_model.dart';
import '../../enums/app_enums.dart';
import '../../services/campaign_service.dart';
import '../../providers/auth_provider.dart';
import '../../config/app_colors.dart';
import '../../theme/app_text_styles.dart';
import '../../theme/app_spacing.dart';
import '../../utils/snackbar_helper.dart';
import '../../widgets/common/custom_button.dart';
import '../../widgets/common/custom_text_field.dart';
import 'package:image_picker/image_picker.dart';
import 'package:google_mlkit_text_recognition/google_mlkit_text_recognition.dart';

class AddExpenseScreen extends StatefulWidget {
  final String campaignId;

  const AddExpenseScreen({super.key, required this.campaignId});

  @override
  State<AddExpenseScreen> createState() => _AddExpenseScreenState();
}

class _AddExpenseScreenState extends State<AddExpenseScreen> {
  final _formKey = GlobalKey<FormState>();
  final _campaignService = CampaignService();

  final _itemNameController = TextEditingController();
  final _quantityController = TextEditingController(text: '1');
  final _unitPriceController = TextEditingController();
  final _vendorController = TextEditingController();
  final _notesController = TextEditingController();

  ExpenseCategory _selectedCategory = ExpenseCategory.other;
  String _selectedUnit = 'pieces';
  bool _isLoading = false;

  final List<String> _units = ['pieces', 'kg', 'liters', 'packs', 'boxes', 'Rs', 'other'];

  @override
  void dispose() {
    _itemNameController.dispose();
    _quantityController.dispose();
    _unitPriceController.dispose();
    _vendorController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _scanReceipt() async {
    final ImagePicker picker = ImagePicker();
    final XFile? image = await picker.pickImage(source: ImageSource.camera);
    if (image == null) return;

    setState(() => _isLoading = true);
    
    try {
      final inputImage = InputImage.fromFilePath(image.path);
      final textRecognizer = TextRecognizer(script: TextRecognitionScript.latin);
      final RecognizedText recognizedText = await textRecognizer.processImage(inputImage);
      
      String extractedText = recognizedText.text.replaceAll(',', '');
      
      // Simple regex to find amounts
      RegExp exp = RegExp(r'(?:total|amount|rs|pkr|sum)?\s*[:\-\=]?\s*(\d+(?:\.\d{1,2})?)', caseSensitive: false);
      Iterable<RegExpMatch> matches = exp.allMatches(extractedText);
      
      double maxAmount = 0.0;
      for (final m in matches) {
        if (m.group(1) != null) {
          double val = double.tryParse(m.group(1)!) ?? 0.0;
          if (val > maxAmount) maxAmount = val;
        }
      }
      
      await textRecognizer.close();

      if (maxAmount > 0) {
        if (mounted) {
          setState(() {
            _unitPriceController.text = maxAmount.toString();
          });
          SnackbarHelper.showSuccess(context, 'Extracted Amount: $maxAmount');
        }
      } else {
        if (mounted) SnackbarHelper.showError(context, 'Could not detect an amount clearly.');
      }
    } catch (e) {
      if (mounted) SnackbarHelper.showError(context, 'OCR Failed: $e');
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _submitExpense() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final user = context.read<AuthProvider>().user!;
      final qty = int.parse(_quantityController.text.trim());
      final price = double.parse(_unitPriceController.text.trim());
      final total = qty * price;

      final expense = ExpenseModel(
        id: '', // Generated by Firestore
        campaignId: widget.campaignId,
        itemName: _itemNameController.text.trim(),
        category: _selectedCategory,
        quantity: qty,
        unit: _selectedUnit,
        unitPrice: price,
        totalAmount: total,
        vendor: _vendorController.text.trim().isEmpty ? null : _vendorController.text.trim(),
        notes: _notesController.text.trim().isEmpty ? null : _notesController.text.trim(),
        addedBy: user.uid,
        addedByName: user.name,
        createdAt: DateTime.now(),
      );

      await _campaignService.addExpense(expense);

      if (mounted) {
        SnackbarHelper.showSuccess(context, 'Expense recorded successfully!');
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        SnackbarHelper.showError(context, 'Failed to add expense: $e');
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Add Expense', style: AppTextStyles.titleLarge())),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(AppSpacing.lg),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('Expense Details', style: AppTextStyles.titleLarge()),
                  TextButton.icon(
                    onPressed: _isLoading ? null : _scanReceipt,
                    icon: const Icon(Icons.document_scanner),
                    label: const Text('Scan Receipt'),
                  ),
                ],
              ),
              AppSpacing.vGapLg,
              
              CustomTextField(
                controller: _itemNameController,
                label: 'Item Name',
                hint: 'e.g., Blankets, Transport, Food Boxes',
                prefixIcon: Icons.shopping_bag,
                validator: (val) => val == null || val.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 16),
              
              DropdownButtonFormField<ExpenseCategory>(
                // ignore: deprecated_member_use
                value: _selectedCategory,
                decoration: const InputDecoration(
                  labelText: 'Category',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.category),
                ),
                items: ExpenseCategory.values.map((cat) {
                  return DropdownMenuItem(
                    value: cat,
                    child: Text('${cat.icon} ${cat.label}'),
                  );
                }).toList(),
                onChanged: (val) => setState(() => _selectedCategory = val!),
              ),
              const SizedBox(height: 16),

              Row(
                children: [
                  Expanded(
                    flex: 2,
                    child: CustomTextField(
                      controller: _quantityController,
                      label: 'Quantity',
                      keyboardType: TextInputType.number,
                      prefixIcon: Icons.numbers,
                      validator: (val) {
                        if (val == null || val.isEmpty) return 'Required';
                        if (int.tryParse(val) == null) return 'Invalid number';
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    flex: 3,
                    child: DropdownButtonFormField<String>(
                      // ignore: deprecated_member_use
                      value: _selectedUnit,
                      decoration: const InputDecoration(
                        labelText: 'Unit',
                        border: OutlineInputBorder(),
                      ),
                      items: _units.map((unit) {
                        return DropdownMenuItem(value: unit, child: Text(unit));
                      }).toList(),
                      onChanged: (val) => setState(() => _selectedUnit = val!),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              CustomTextField(
                controller: _unitPriceController,
                label: 'Unit Price (Rs.)',
                hint: 'Price per item',
                keyboardType: TextInputType.number,
                prefixIcon: Icons.attach_money,
                validator: (val) {
                  if (val == null || val.isEmpty) return 'Required';
                  if (double.tryParse(val) == null) return 'Invalid price';
                  return null;
                },
              ),
              const SizedBox(height: 24),

              const Text('Optional Information', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              const SizedBox(height: 16),

              CustomTextField(
                controller: _vendorController,
                label: 'Vendor / Shop Name',
                prefixIcon: Icons.store,
              ),
              const SizedBox(height: 16),

              CustomTextField(
                controller: _notesController,
                label: 'Notes',
                maxLines: 3,
                hint: 'Any additional details or receipt reference',
              ),
              const SizedBox(height: 32),

              CustomButton(
                text: 'Record Expense',
                isLoading: _isLoading,
                onPressed: _submitExpense,
                backgroundColor: AppColors.error, // Red color for expense
              ),
              const SizedBox(height: 32),
            ],
          ),
        ),
      ),
    );
  }
}
