import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../models/distribution_model.dart';
import '../../services/distribution_service.dart';
import '../../providers/auth_provider.dart';
import '../../config/app_colors.dart';
import '../../utils/snackbar_helper.dart';
import '../../widgets/common/custom_button.dart';
import '../../widgets/common/custom_text_field.dart';

class AddDistributionScreen extends StatefulWidget {
  final String campaignId;

  const AddDistributionScreen({super.key, required this.campaignId});

  @override
  State<AddDistributionScreen> createState() => _AddDistributionScreenState();
}

class _AddDistributionScreenState extends State<AddDistributionScreen> {
  final _formKey = GlobalKey<FormState>();
  final _distributionService = DistributionService();

  final _quantityController = TextEditingController(text: '1');
  final _distributedToController = TextEditingController(text: '1');
  final _locationController = TextEditingController();
  final _notesController = TextEditingController();

  String _selectedItemType = 'blankets';
  String _selectedUnit = 'pieces';
  bool _isLoading = false;

  final List<String> _itemTypes = ['blankets', 'food', 'clothes', 'money', 'medicine', 'other'];
  final List<String> _units = ['pieces', 'kg', 'packs', 'boxes', 'Rs', 'liters'];

  @override
  void dispose() {
    _quantityController.dispose();
    _distributedToController.dispose();
    _locationController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _submitDistribution() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final user = context.read<AuthProvider>().user!;
      final qty = int.parse(_quantityController.text.trim());
      final distributedTo = int.parse(_distributedToController.text.trim());

      final distribution = DistributionModel(
        id: '', // Generated by Firestore
        campaignId: widget.campaignId,
        itemType: _selectedItemType,
        quantity: qty,
        unit: _selectedUnit,
        distributedTo: distributedTo,
        distributedBy: user.uid,
        distributedAt: DateTime.now(),
        location: _locationController.text.trim(),
        notes: _notesController.text.trim().isEmpty ? null : _notesController.text.trim(),
      );

      await _distributionService.addDistribution(distribution);

      if (mounted) {
        SnackbarHelper.showSuccess(context, 'Distribution recorded successfully!');
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        SnackbarHelper.showError(context, 'Failed to add distribution: $e');
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Add Distribution')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text('Distribution Details', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              const SizedBox(height: 16),
              
              Row(
                children: [
                  Expanded(
                    flex: 1,
                    child: DropdownButtonFormField<String>(
                      // ignore: deprecated_member_use
                      value: _selectedItemType,
                      decoration: const InputDecoration(
                        labelText: 'Item Type',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.category),
                      ),
                      items: _itemTypes.map((type) {
                        return DropdownMenuItem(
                          value: type,
                          child: Text(type.toUpperCase()),
                        );
                      }).toList(),
                      onChanged: (val) => setState(() => _selectedItemType = val!),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              
              Row(
                children: [
                  Expanded(
                    flex: 2,
                    child: CustomTextField(
                      controller: _quantityController,
                      label: 'Total Quantity',
                      keyboardType: TextInputType.number,
                      prefixIcon: Icons.numbers,
                      validator: (val) {
                        if (val == null || val.isEmpty) return 'Required';
                        if (int.tryParse(val) == null || int.parse(val) < 1) return 'Invalid';
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    flex: 2,
                    child: DropdownButtonFormField<String>(
                      // ignore: deprecated_member_use
                      value: _selectedUnit,
                      decoration: const InputDecoration(
                        labelText: 'Unit',
                        border: OutlineInputBorder(),
                      ),
                      items: _units.map((unit) {
                        return DropdownMenuItem(value: unit, child: Text(unit));
                      }).toList(),
                      onChanged: (val) => setState(() => _selectedUnit = val!),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              CustomTextField(
                controller: _distributedToController,
                label: 'Distributed To (Count of Families/People)',
                keyboardType: TextInputType.number,
                prefixIcon: Icons.people_alt,
                validator: (val) {
                  if (val == null || val.isEmpty) return 'Required';
                  if (int.tryParse(val) == null || int.parse(val) < 1) return 'Invalid';
                  return null;
                },
              ),
              const SizedBox(height: 16),

              CustomTextField(
                controller: _locationController,
                label: 'Distribution Location',
                prefixIcon: Icons.location_on,
                validator: (val) => val == null || val.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 24),

              const Text('Optional Information', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              const SizedBox(height: 16),

              CustomTextField(
                controller: _notesController,
                label: 'Notes',
                maxLines: 3,
                hint: 'Specific areas, issues faced, or general remarks',
              ),
              const SizedBox(height: 32),

              CustomButton(
                text: 'Record Distribution',
                isLoading: _isLoading,
                onPressed: _submitDistribution,
                backgroundColor: AppColors.success, // Green color
              ),
              const SizedBox(height: 32),
            ],
          ),
        ),
      ),
    );
  }
}
