import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../models/beneficiary_model.dart';
import '../../services/distribution_service.dart';
import '../../providers/auth_provider.dart';
import '../../config/app_colors.dart';
import '../../utils/snackbar_helper.dart';
import '../../widgets/common/custom_button.dart';
import '../../widgets/common/custom_text_field.dart';

class AddBeneficiaryScreen extends StatefulWidget {
  final String campaignId;

  const AddBeneficiaryScreen({super.key, required this.campaignId});

  @override
  State<AddBeneficiaryScreen> createState() => _AddBeneficiaryScreenState();
}

class _AddBeneficiaryScreenState extends State<AddBeneficiaryScreen> {
  final _formKey = GlobalKey<FormState>();
  final _distributionService = DistributionService();

  final _nameController = TextEditingController();
  final _phoneController = TextEditingController();
  final _addressController = TextEditingController();
  final _familySizeController = TextEditingController(text: '1');
  final _itemsReceivedController = TextEditingController();
  final _notesController = TextEditingController();

  bool _isLoading = false;

  @override
  void dispose() {
    _nameController.dispose();
    _phoneController.dispose();
    _addressController.dispose();
    _familySizeController.dispose();
    _itemsReceivedController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _submitBeneficiary() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final user = context.read<AuthProvider>().user!;
      final familySize = int.parse(_familySizeController.text.trim());

      final beneficiary = BeneficiaryModel(
        id: '', // Generated by Firestore
        campaignId: widget.campaignId,
        name: _nameController.text.trim(),
        phone: _phoneController.text.trim().isEmpty ? null : _phoneController.text.trim(),
        address: _addressController.text.trim(),
        familySize: familySize,
        itemsReceived: _itemsReceivedController.text.trim(),
        receivedAt: DateTime.now(),
        notes: _notesController.text.trim().isEmpty ? null : _notesController.text.trim(),
        addedBy: user.uid,
      );

      await _distributionService.addBeneficiary(beneficiary);

      if (mounted) {
        SnackbarHelper.showSuccess(context, 'Beneficiary added successfully!');
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        SnackbarHelper.showError(context, 'Failed to add beneficiary: $e');
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Add Beneficiary')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text('Beneficiary Information', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              const SizedBox(height: 16),
              
              CustomTextField(
                controller: _nameController,
                label: 'Head of Family Name / Individual Name',
                prefixIcon: Icons.person,
                validator: (val) => val == null || val.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 16),
              
              Row(
                children: [
                  Expanded(
                    flex: 2,
                    child: CustomTextField(
                      controller: _familySizeController,
                      label: 'Family Size',
                      keyboardType: TextInputType.number,
                      prefixIcon: Icons.group,
                      validator: (val) {
                        if (val == null || val.isEmpty) return 'Required';
                        if (int.tryParse(val) == null || int.parse(val) < 1) return 'Invalid';
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    flex: 3,
                    child: CustomTextField(
                      controller: _phoneController,
                      label: 'Phone Number',
                      keyboardType: TextInputType.phone,
                      prefixIcon: Icons.phone,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              CustomTextField(
                controller: _addressController,
                label: 'Address / Location',
                prefixIcon: Icons.location_on,
                validator: (val) => val == null || val.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 24),

              const Text('Assistance Provided', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              const SizedBox(height: 16),

              CustomTextField(
                controller: _itemsReceivedController,
                label: 'Items Received',
                hint: 'e.g., 2 Blankets, 1 Ration Pack',
                prefixIcon: Icons.inventory_2,
                validator: (val) => val == null || val.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 16),

              CustomTextField(
                controller: _notesController,
                label: 'Additional Notes',
                maxLines: 3,
                hint: 'Any specific condition, CNIC info, or reference',
              ),
              const SizedBox(height: 32),

              CustomButton(
                text: 'Save Beneficiary Record',
                isLoading: _isLoading,
                onPressed: _submitBeneficiary,
                backgroundColor: AppColors.info, // Blue color for beneficiary
              ),
              const SizedBox(height: 32),
            ],
          ),
        ),
      ),
    );
  }
}
