import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import '../../config/app_colors.dart';
import '../../theme/app_text_styles.dart';
import '../../theme/app_spacing.dart';
import '../../theme/app_tokens.dart';
import '../../services/qr_service.dart';

/// Volunteer screen to scan a campaign QR code for attendance.
///
/// Uses the device camera to scan QR codes generated by admins.
/// Only works on mobile (Android/iOS) — not available on Web.
class QrScanScreen extends StatefulWidget {
  final String userId;
  final String userName;

  const QrScanScreen({
    super.key,
    required this.userId,
    required this.userName,
  });

  @override
  State<QrScanScreen> createState() => _QrScanScreenState();
}

class _QrScanScreenState extends State<QrScanScreen> {
  MobileScannerController? _controller;
  bool _isProcessing = false;
  QrScanResult? _result;

  @override
  void initState() {
    super.initState();
    if (!kIsWeb) {
      _controller = MobileScannerController(
        detectionSpeed: DetectionSpeed.normal,
        facing: CameraFacing.back,
      );
    }
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }

  void _onDetect(BarcodeCapture capture) async {
    if (_isProcessing) return;
    final barcode = capture.barcodes.firstOrNull;
    if (barcode == null || barcode.rawValue == null) return;

    setState(() => _isProcessing = true);
    _controller?.stop();

    final result = await QrService.markAttendance(
      qrRawData: barcode.rawValue!,
      userId: widget.userId,
      userName: widget.userName,
    );

    if (mounted) {
      setState(() => _result = result);
    }
  }

  void _resetScanner() {
    setState(() {
      _isProcessing = false;
      _result = null;
    });
    _controller?.start();
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      appBar: AppBar(
        title: Text('Scan QR Code', style: AppTextStyles.titleLarge()),
        centerTitle: true,
      ),
      body: kIsWeb
          ? _buildWebFallback(isDark)
          : _result != null
              ? _buildResultView(isDark)
              : _buildScannerView(),
    );
  }

  Widget _buildWebFallback(bool isDark) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.qr_code_scanner, size: 64, color: AppColors.lightTextHint),
          AppSpacing.vGapLg,
          Text('QR Scanner is only available on mobile',
              style: AppTextStyles.bodyLarge(color: AppColors.lightTextSecondary)),
          AppSpacing.vGapSm,
          Text('Please use the Android or iOS app to scan QR codes',
              style: AppTextStyles.bodyMedium(color: AppColors.lightTextHint)),
        ],
      ),
    );
  }

  Widget _buildScannerView() {
    return Stack(
      children: [
        MobileScanner(
          controller: _controller!,
          onDetect: _onDetect,
        ),
        // Overlay with scan area indicator
        Center(
          child: Container(
            width: 250,
            height: 250,
            decoration: BoxDecoration(
              border: Border.all(color: AppColors.primary, width: 3),
              borderRadius: AppTokens.borderRadiusLg,
            ),
          ),
        ),
        // Bottom instruction
        Positioned(
          bottom: 40,
          left: 0,
          right: 0,
          child: Center(
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: AppSpacing.xl, vertical: AppSpacing.md),
              decoration: BoxDecoration(
                color: Colors.black54,
                borderRadius: AppTokens.borderRadiusPill,
              ),
              child: Text(
                'Point camera at the campaign QR code',
                style: AppTextStyles.bodyMedium(color: Colors.white),
              ),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildResultView(bool isDark) {
    final result = _result!;
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(AppSpacing.xl),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              padding: const EdgeInsets.all(AppSpacing.xxl),
              decoration: BoxDecoration(
                color: (result.success ? AppColors.success : AppColors.error).withValues(alpha: 0.1),
                shape: BoxShape.circle,
              ),
              child: Icon(
                result.success ? Icons.check_circle : Icons.error,
                size: 72,
                color: result.success ? AppColors.success : AppColors.error,
              ),
            ),
            AppSpacing.vGapXxl,
            Text(
              result.success ? 'Attendance Marked!' : 'Scan Failed',
              style: AppTextStyles.displaySmall(
                color: result.success ? AppColors.success : AppColors.error,
              ),
            ),
            AppSpacing.vGapMd,
            Text(
              result.message,
              style: AppTextStyles.bodyLarge(
                color: isDark ? AppColors.darkTextSecondary : AppColors.lightTextSecondary,
              ),
              textAlign: TextAlign.center,
            ),
            AppSpacing.vGapXxl,
            FilledButton.icon(
              onPressed: _resetScanner,
              icon: const Icon(Icons.qr_code_scanner),
              label: const Text('Scan Another'),
              style: FilledButton.styleFrom(
                padding: const EdgeInsets.symmetric(horizontal: AppSpacing.xxl, vertical: AppSpacing.lg),
              ),
            ),
            AppSpacing.vGapMd,
            OutlinedButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Done'),
            ),
          ],
        ),
      ),
    );
  }
}
